# Generated by Django 3.2.12 on 2022-03-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niq', '0002_auto_20220328_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Location',
            new_name='location',
        ),
    ]
